src/Entity/Episode.php
<?php

namespace App\Entity;

use App\Repository\EpisodeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EpisodeRepository::class)]
class Episode
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $season_id = null;

    #[ORM\Column(length: 200)]
    private ?string $title = null;

    #[ORM\Column]
    private ?int $number = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $synopsis = null;

    #[ORM\ManyToOne(inversedBy: 'episodes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Season $season = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSeasonId(): ?int
    {
        return $this->season_id;
    }

    public function setSeasonId(int $season_id): self
    {
        $this->season_id = $season_id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getSeason(): ?Season
    {
        return $this->season;
    }

    public function setSeason(?Season $season): self
    {
        $this->season = $season;

        return $this;
    }
}

src/Form/EpisodeType.php
<?php

namespace App\Form;

use App\Entity\Episode;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EpisodeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('number')
            ->add('synopsis')
            ->add('season', null, ['choice_label' => 'programSeason']);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Episode::class,
        ]);
    }
}

src/Controller/EpisodeController.php
<?php

namespace App\Controller;

use App\Entity\Episode;
use App\Form\EpisodeType;
use App\Repository\EpisodeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/episode')]
class EpisodeController extends AbstractController
{
    #[Route('/', name: 'app_episode_index', methods: ['GET'])]
    public function index(EpisodeRepository $episodeRepository): Response
    {
        return $this->render('episode/index.html.twig', [
            'episodes' => $episodeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_episode_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EpisodeRepository $episodeRepository): Response
    {
        $episode = new Episode();
        $form = $this->createForm(EpisodeType::class, $episode);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $episodeRepository->save($episode, true);

            return $this->redirectToRoute('app_episode_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('episode/new.html.twig', [
            'episode' => $episode,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_episode_show', methods: ['GET'])]
    public function show(Episode $episode): Response
    {
        return $this->render('episode/show.html.twig', [
            'episode' => $episode,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_episode_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Episode $episode, EpisodeRepository $episodeRepository): Response
    {
        $form = $this->createForm(EpisodeType::class, $episode);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $episodeRepository->save($episode, true);

            return $this->redirectToRoute('app_episode_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('episode/edit.html.twig', [
            'episode' => $episode,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_episode_delete', methods: ['POST'])]
    public function delete(Request $request, Episode $episode, EpisodeRepository $episodeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$episode->getId(), $request->request->get('_token'))) {
            $episodeRepository->remove($episode, true);
        }

        return $this->redirectToRoute('app_episode_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/episode/_delete_form.html.twig
<form method="post" action="{{ path('app_episode_delete', {'id': episode.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ episode.id) }}">
    <button class="btn">Delete</button>
</form>

templates/episode/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/episode/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Episode{% endblock %}

{% block body %}
    <h1>Edit Episode</h1>

    {{ include('episode/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_episode_index') }}">back to list</a>

    {{ include('episode/_delete_form.html.twig') }}
{% endblock %}

templates/episode/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Episode index
{% endblock %}

{% block body %}
	<h1>Episode index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Season id</th>
				<th>Title</th>
				<th>Number</th>
				<th>Synopsis</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for episode in episodes %}
				<tr>
					<td>{{ episode.id }}</td>
					<td>{{ episode.season.id }}</td>
					<td>{{ episode.title }}</td>
					<td>{{ episode.number }}</td>
					<td>{{ episode.synopsis }}</td>
					<td>
						<a href="{{ path('app_episode_show', {'id': episode.id}) }}">show</a>
						<a href="{{ path('app_episode_edit', {'id': episode.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="6">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_episode_new') }}">Create new</a>
{% endblock %}

templates/episode/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Episode{% endblock %}

{% block body %}
    <h1>Create new Episode</h1>

    {{ include('episode/_form.html.twig') }}

    <a href="{{ path('app_episode_index') }}">back to list</a>
{% endblock %}

templates/episode/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Episode{% endblock %}

{% block body %}
    <h1>Episode</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ episode.id }}</td>
            </tr>
            <tr>
                <th>Season_id</th>
                <td>{{ episode.seasonId }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ episode.title }}</td>
            </tr>
            <tr>
                <th>Number</th>
                <td>{{ episode.number }}</td>
            </tr>
            <tr>
                <th>Synopsis</th>
                <td>{{ episode.synopsis }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_episode_index') }}">back to list</a>

    <a href="{{ path('app_episode_edit', {'id': episode.id}) }}">edit</a>

    {{ include('episode/_delete_form.html.twig') }}
{% endblock %}